### ISSUE TITLE
Command ID

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#151] opened 2018-12-11 03:18 UTC
LS-094 (https://www.oasis-open.org/apps/org/workgroup/openc2/email/archives/201812/msg00023.html as corrected by https://www.oasis-open.org/apps/org/workgroup/openc2/email/archives/201812/msg00046.html):

> Page 12 lines 16ish-29ish Section 2.1 (and equivalent property tables in section 3)
> 
> Previous versions of this specification had and optional ‘Command_ID’ in addition to Action/Target/Args/Actuator.
> 
> I propose to add back in the optional command_id.
> 
> It was replaced by the use of the ‘request_id’ (see page 17 line 14ish) which is in the message header and not in the JSON content. I agree the request_id is the proper field to use for matching requests and responses. However, I disagree with it’s use with action=cancel and the other actions that need a reference to a previous command. JSON content of a command should not be dependent on transport header information. This breaks ’transport agnostic’ IMHO. I recognize models/analogies are all wrong - but as the famous quote say, some are useful. Using the letter (ie our JSON content) and envelope (the message header handled by transport) - almost all letters start with some sort of salutation with the name of the person addressed. I.e. ‘Dear John’ lets you know the letter is for ‘John’. Similarly I think the action=cancel command should refer to an id within in the JSON.
> 
> I feel strongly on this topic. Unfortunately I could not attend the Face-to-Face where this was discussed. My reading of the notes lead me to believe there is still concern on breaking transport agnostic. I would like, if possible, an informal polling (maybe with comments on GitHub or on a wiki page) with participants answering:
> * Strongly agree with adding optional command_id
> * Prefer (but not strongly) adding optional command_id
> * Ok either way
> * Prefer (but not strongly) current wording without command_id
> * Strongly disagree with adding optional command_id
> 
> Note I am NOT proposing to change the use of request_id wrt responses – only wrt affecting ‘inside the JSON’.
>  
> I believe there are enough people in the “ok either way” and ‘Prefer (but not strongly)’ to warrant reopening the issue even though no one ‘objected’ at the meeting to removing command_id. I would have objected if present. I will withdraw on this topic is the survey shows a clear preponderance of people strongly (or weakly) disagree with my proposal. However I will remain vocal (and vote NO) if it is 1 strongly agree (myself) and 1 strongly disagree and everyone else is ‘ok either way’.

**Comment by jmbrule** [comment] 2018-12-19 13:14
I cannot participate in the straw poll from my work machine, probably could from home but these machines are tightened down. 
BTW, either solution is workable, but disagree that the command_id should be a part of the JSON.

**Comment by davaya** [comment] 2018-12-19 15:09
Command identifiers should remain outside of the command because:

1. OpenC2-Command is the core cybersecurity function to be performed.  That function is defined by the action/target/actuator/args.   Sending commands from producers to consumers, identifying and authenticating commands, logging and auditing commands, using commands in COAs and workflows, etc are all essential functions but they are independent of the atomic cybersecurity operation defined by a command.

2. The requirements for what a command identifier needs to contain are driven by communication and workflow considerations, not by the cybersecurity function to be performed.  Consider three scenarios:
  (a) a single command from a producer to one or more consumers
  (b) a list of commands from a producer to one or more consumers, all of which need to be executed but some of which may be individually referenced or cancelled
  (c) a COA where commands are part of a script, where execution of some may depend on the results of others, where destinations may be different for different commands (e.g., block traffic on a firewall, delete file on a server, and change registry key on an endpoint).   We haven't started defining COAs yet.

Assume that case (a) requires command IDs to be globally unique, and the mandatory format is UUID. Whether the UUID is inside the or outside the command doesn't make much difference.

But for case (b), it makes a big difference.  A single message with 20 commands can uniquely identify each command with 1 UUID for the message (outside the command), or with 20 UUIDs (one inside each command).   Cancelling the 5th command of a multi-command message could be done by `cancel ebed5b0f-0369-48fe-b5ba-a54eba587542[5]`

Putting the identifier inside the command forces producers to generate 20 UUIDs instead of 1, and the overhead of putting a UUID inside each message is huge - the identifier could be larger than the message itself.

Putting the identifier outside the command **allows** producers to use only one UUID for a list of commands, but it also **allows** producers to tag each message with an individual UUID if the communications use case makes that preferable.

Define the cybersecurity function inside the command.  Define the workflow functions outside the command - decisions on whether a command ID is required or optional, whether it must be globally unique or unique within a system, whether it must be a UUID or something else - those do not affect the command.  They affect the messages, command lists, or COAs that make use of the command.

**Comment by alevere** [comment] 2018-12-19 17:04
Generally speaking, I agree with Duncan on this.
Some actuators just cannot do what you all are wanting to do here, crossing data between header and payloads.
I am not going to vote unless this is written up exactly as what language is changed in which spec.
E.g. I would like to see the diff in a pull request.

**Comment by davaya** [comment] 2018-12-19 18:07
The "header vs. payload" question is unrelated to the "inside or outside the command" question.

The Language Spec defines the fields of a message, which every transfer spec must define how transmit.

The HTTP transfer spec puts those fields in http headers.  (Even https://www.gnu.org/software/libmicrohttpd/ supports setting and reading http headers.)

A different HTTP transfer spec, or a modification to the one currently under public review, could put all of those fields in a payload.

**Comment by sparrell** [comment] 2018-12-31 11:45
wrt @alevere comment "I am not going to vote unless this is written up exactly as what language is changed in which spec". I would note that the change I'm proposing is to go back to the way the command_id was in the JSON until relatively recently. I didn't want to do the work of all the changes (it's in several places) unless it was agreed in principle to be worth it. The quick and dirty summary is to look at example 2 in CSD06 (the October 2018 version of LS) at http://docs.oasis-open.org/openc2/oc2ls/v1.0/csd05/oc2ls-v1.0-csd05.html#92_Example_2_1001 which contains the command_id in the JSON.

**Comment by sparrell** [comment] 2018-12-31 11:55
wrt @davaya comment that "Command identifiers should remain outside of the (JSON)": I disagree. The ID is what identifies that particular command. I maintain there is less chance of mistaken identity if the ID is in the JSON. Note I am NOT asking for the removal of the transport-related ID. But if there is an ID inside the JSON then you can be assured which command you are talking about.

**Comment by sparrell** [comment] 2018-12-31 12:00
wrt @davaya comment 

> But for case (b), it makes a big difference. A single message with 20 commands can uniquely identify each command with 1 UUID for the message (outside the command), or with 20 UUIDs (one inside each command). Cancelling the 5th command of a multi-command message could be done by cancel ebed5b0f-0369-48fe-b5ba-a54eba587542[5]
I strongly believe 20 ID's are needed for 20 commands. We have not yet addressed the topic of 'playbooks' and sequencing multiple commands (with @davaya's organization being the most vocal about deferring the discussion until post-1.0) so I disagree even with the premise that it is a 1.0 requirement. But if it were, I do think each unique id's are needed for the case described instead of adding '[5]' (which by the way is making a unique ID from a non-unique ID).

**Comment by davaya** [comment] 2019-01-22 19:38
The Message Elements in section 3.2 are the mechanism that allows OpenC2 to remain decoupled from transfer specifications.   We have only one transfer spec now, but we've just added two more (MQTT and OpenDXL) to our list of work products.

Request_id is not something needed in the future to support multiple commands per message, it is the message element used today to support a single command per message in a transport-protocol-agnostic* manner.

All of your bullets are as we agreed at the F2F.  The only omission is the simplification that cannot be made - a request_id must be present in every message for which a response is expected.

So you need a bullet 1.5: if a Consumer receives a command that does not contain a command_id, the consumer MUST use the value of the request_id as the command_id.   If, after step 1.5 the command_id is still not specified (meaning the producer sent a message with neither a request_id nor a command_id), then your bullet 2 takes effect (Consumers can, at their discretion, assign a new command_id).

----
* As we discussed at the F2F, **transport** is a stack of layer 5 and below communication protocols, while **transfer** is an OpenC2-defined mechanism to convey application data over those lower layers.

**Comment by romanojd** [comment] 2019-01-28 11:20
Per the LSC Meeting, 1/22/2019, we agreed to add a bullet for the default case and add a sentence to state that UUID SHOULD be used.

**Comment by davaya** [comment] 2019-01-28 20:08
Pull request submitted: https://github.com/oasis-tcs/openc2-oc2ls/pull/248/files

**Comment by davaya** [comment] 2019-02-05 18:02
- The 0-128 was inspired by COAP https://tools.ietf.org/html/rfc7252#section-5.3.1:

>    The Token is used to match a response with a request.  The token
>    value is a sequence of 0 to 8 bytes.  (Note that every message
>    carries a token, even if it is of zero length.)

But since request_id and command_id are optional, there should be a non-zero lower bound.  Suggest "a value of 1-16 bytes".

- Like JADN, Messages are used by but not exclusive to v1.0 of the Language.  JADN is being moved to a different spec now, and Messages may be moved to a different spec in the future.  But even LS v1.0 defines notifications even if it doesn't use the word: Section 3.4.2.11 "Response Type" includes a **none** option.  A command containing this response type would be carried in a Notification message - the producer MUST NOT wait for a response and the consumer MUST NOT send one.

- The request_id message element identifies a request.  The command_id field of an OpenC2-Command identifies a command.   A message with a request_id can contain a command with a command_id having a different value.  Both request_id and command_id are of type RCID.  Any confusion would be caused by populating command_id with a different value from the request_id.  But it should not be confusing that both values have the same type.

**Comment by romanojd** [comment] 2019-02-06 03:10
LSC Meeting, 2/05/2019: We're getting closer, but haven't quite reached consensus yet.

**Comment by romanojd** [comment] 2019-02-06 03:11
I, personally, think that we should call the datatype `Identifier` instead of `RCID`. It seems to match the conventions set by the other datatypes.

**Comment by dlemire60** [comment] 2019-02-06 14:26
> But since request_id and command_id are optional, there should be a non-zero lower bound. Suggest "a value of 1-16 bytes".

That seems reasonable.

> * But even LS v1.0 defines notifications even if it doesn't use the word: Section 3.4.2.11 "Response Type" includes a **none** option.  

OK, point taken.

> * But it should not be confusing that both values have the same type.

I didn't think using the same data type for both was confusing. I was interpreting the decision from the F2F in a particular way, but now that I reread your PR text I realize my concern was misplaced. OTOH, it could be worded as (incorporating Jason's comment):

| **identifier** | Binary | A value of up to 128 bits used as a unique identifier |

which leaves the door open to possible other uses of identifiers should they come to light.

**Comment by bberliner** [comment] 2019-02-06 15:54
Just FYI. We are focused on using IETF standards for these kinds of things and we use UUIDv4 string identifiers universally in our platform (I pretty positive that we are not alone in that assertion), so our Consumers will be accepting UUIDv4 identifier strings as their “command_id” and/or “request_id” fields, regardless of what our spec eventually requires. According to the RFC, that is 36 bytes: https://tools.ietf.org/html/rfc4122#section-3,. I think it would be a mistake if we make a compliance statement that says that these identifiers cannot be serialized as standard UUIDv4 strings.

Also, I think it is a mistake to require Producers to generate a non-standard unique Identifier when they fill in a “command_id” or a “request_id” field, as the standard tools do not support that today. I do not think that any conformance requirements should require the Identifier to be 16 bytes or less when serialized, since that would not allow for them to be standard UUIDv4 strings.



I’m not saying that they MUST be UUIDv4 strings. Only that the spec should not force them to NOT be UUIDv4 strings. That would be the mistake.

Cheers,

                -Brian

**Comment by davaya** [comment] 2019-02-06 16:23
Removed RCID - this eliminates both the question of what to call it and the need to define a size.
- request_id is type String
- command_id is type String

This allows those identifiers to be anything, including UUID, used in the customer's enterprise.

**Comment by romanojd** [comment] 2019-02-12 17:52
I put together an example use-case to review at the LSC Meeting, 2/12/2019.
https://github.com/oasis-tcs/openc2-usecases/blob/master/General/example-identifiers.md

**Comment by romanojd** [comment] 2019-03-13 03:06
LSC Meeting, 3/12/2019: There were no objections to applying pull request #248 and closing this issue.

**Closed** 2019-03-13 03:07 UTC
Labels: group_command-id, v1.0-csprd01
